export const TOOLS = [
  { slug: 'merge-pdf', name: 'Merge PDF', category: 'Organize', description: 'Combine multiple PDFs into one document.' },
  { slug: 'split-pdf', name: 'Split PDF', category: 'Organize', description: 'Extract pages or split a PDF into multiple files.' },
  { slug: 'remove-pages', name: 'Remove Pages', category: 'Organize', description: 'Delete unwanted pages from a PDF.' },
  { slug: 'extract-pages', name: 'Extract Pages', category: 'Organize', description: 'Pull specific pages into a new PDF.' },
  { slug: 'organize-pdf', name: 'Organize PDF', category: 'Organize', description: 'Reorder, rotate, and arrange pages.' },
  { slug: 'rotate-pdf', name: 'Rotate PDF', category: 'Organize', description: 'Rotate pages to the correct orientation.' },
  { slug: 'compress-pdf', name: 'Compress PDF', category: 'Optimize', description: 'Reduce PDF file size while keeping quality.' },
  { slug: 'repair-pdf', name: 'Repair PDF', category: 'Optimize', description: 'Fix a corrupted or damaged PDF file.' },
  { slug: 'ocr-pdf', name: 'OCR PDF', category: 'Optimize', description: 'Make scanned PDFs searchable and selectable.' },
  { slug: 'pdf-to-word', name: 'PDF to Word', category: 'Convert', description: 'Convert PDF documents to editable Word files.' },
  { slug: 'pdf-to-excel', name: 'PDF to Excel', category: 'Convert', description: 'Convert PDF tables into Excel spreadsheets.' },
  { slug: 'pdf-to-powerpoint', name: 'PDF to PowerPoint', category: 'Convert', description: 'Convert PDF slides into editable presentations.' },
  { slug: 'pdf-to-jpg', name: 'PDF to JPG', category: 'Convert', description: 'Turn PDF pages into JPG images.' },
  { slug: 'pdf-to-pdfa', name: 'PDF to PDF/A', category: 'Convert', description: 'Convert to the archival PDF/A format.' },
  { slug: 'word-to-pdf', name: 'Word to PDF', category: 'Convert', description: 'Convert Word documents to PDF.' },
  { slug: 'excel-to-pdf', name: 'Excel to PDF', category: 'Convert', description: 'Convert Excel spreadsheets to PDF.' },
  { slug: 'powerpoint-to-pdf', name: 'PowerPoint to PDF', category: 'Convert', description: 'Convert presentations to PDF.' },
  { slug: 'jpg-to-pdf', name: 'JPG to PDF', category: 'Convert', description: 'Convert JPG images into a PDF document.' },
  { slug: 'html-to-pdf', name: 'HTML to PDF', category: 'Convert', description: 'Convert web pages to PDF.' },
  { slug: 'edit-pdf', name: 'Edit PDF', category: 'Edit', description: 'Add text, images, and shapes to a PDF.' },
  { slug: 'add-page-numbers', name: 'Add Page Numbers', category: 'Edit', description: 'Insert page numbers into your PDF.' },
  { slug: 'add-watermark', name: 'Add Watermark', category: 'Edit', description: 'Stamp a text or image watermark on your PDF.' },
  { slug: 'crop-pdf', name: 'Crop PDF', category: 'Edit', description: 'Crop the margins and pages of a PDF.' },
  { slug: 'sign-pdf', name: 'Sign PDF', category: 'Security', description: 'Add your signature to a PDF document.' },
  { slug: 'protect-pdf', name: 'Protect PDF', category: 'Security', description: 'Add a password to secure your PDF.' },
  { slug: 'unlock-pdf', name: 'Unlock PDF', category: 'Security', description: 'Remove a password from a protected PDF.' },
  { slug: 'redact-pdf', name: 'Redact PDF', category: 'Security', description: 'Permanently black out sensitive content.' },
  { slug: 'compare-pdf', name: 'Compare PDF', category: 'Security', description: 'Compare two PDF files for differences.' },
  { slug: 'scan-to-pdf', name: 'Scan to PDF', category: 'Convert', description: 'Turn scanned images into a PDF.' },
  { slug: 'pdf-to-pdfa-validate', name: 'Validate PDF/A', category: 'Optimize', description: 'Check a PDF for PDF/A compliance.' },
  { slug: 'grayscale-pdf', name: 'Grayscale PDF', category: 'Optimize', description: 'Convert a color PDF to grayscale.' },
  { slug: 'flatten-pdf', name: 'Flatten PDF', category: 'Edit', description: 'Flatten form fields and annotations.' },
  { slug: 'delete-blank-pages', name: 'Delete Blank Pages', category: 'Organize', description: 'Automatically remove blank pages.' },
  { slug: 'n-up-pdf', name: 'N-Up PDF', category: 'Organize', description: 'Combine multiple pages onto one sheet.' },
  { slug: 'pdf-to-text', name: 'PDF to Text', category: 'Convert', description: 'Extract plain text from a PDF.' },
  { slug: 'chat-with-pdf', name: 'Chat with PDF', category: 'AI', description: 'Ask questions about your PDF using AI.' },
  { slug: 'summarize-pdf', name: 'Summarize PDF', category: 'AI', description: 'Get an AI-generated summary of your PDF.' },
];

export const CATEGORIES = [...new Set(TOOLS.map((t) => t.category))];
