// `available: true` tools run real processing (pdf-lib / pdf-parse, no external binaries).
// `available: false` tools need infrastructure this shared-hosting plan doesn't have yet
// (LibreOffice for office conversions, a PDF rasterizer for image export, OCR, or AI) —
// they show an honest "not available yet" message instead of a fake successful download.
export const TOOLS = [
  { slug: 'merge-pdf', name: 'Merge PDF', category: 'Organize', description: 'Combine multiple PDFs into one document.', available: true, multiFile: true },
  { slug: 'split-pdf', name: 'Split PDF', category: 'Organize', description: 'Split a PDF into one file per page (downloaded as a zip).', available: true },
  { slug: 'remove-pages', name: 'Remove Pages', category: 'Organize', description: 'Delete unwanted pages from a PDF.', available: true, formField: { name: 'pages', label: 'Pages to remove (e.g. 1,3,5-7)', placeholder: '1,3,5-7' } },
  { slug: 'extract-pages', name: 'Extract Pages', category: 'Organize', description: 'Pull specific pages into a new PDF.', available: true, formField: { name: 'pages', label: 'Pages to extract (e.g. 1,3,5-7)', placeholder: '1,3,5-7' } },
  { slug: 'organize-pdf', name: 'Organize PDF', category: 'Organize', description: 'Clean up and rebuild a PDF\u2019s internal structure.', available: true },
  { slug: 'rotate-pdf', name: 'Rotate PDF', category: 'Organize', description: 'Rotate every page to the correct orientation.', available: true, formField: { name: 'angle', label: 'Rotate by', type: 'select', options: [['90', '90° clockwise'], ['180', '180°'], ['270', '270° clockwise']] } },
  { slug: 'compress-pdf', name: 'Compress PDF', category: 'Optimize', description: 'Reduce PDF file size while keeping quality.', available: true },
  { slug: 'repair-pdf', name: 'Repair PDF', category: 'Optimize', description: 'Fix a corrupted or damaged PDF file.', available: true },
  { slug: 'ocr-pdf', name: 'OCR PDF', category: 'Optimize', description: 'Make scanned PDFs searchable and selectable.', available: false },
  { slug: 'pdf-to-word', name: 'PDF to Word', category: 'Convert', description: 'Convert PDF documents to editable Word files.', available: false },
  { slug: 'pdf-to-excel', name: 'PDF to Excel', category: 'Convert', description: 'Convert PDF tables into Excel spreadsheets.', available: false },
  { slug: 'pdf-to-powerpoint', name: 'PDF to PowerPoint', category: 'Convert', description: 'Convert PDF slides into editable presentations.', available: false },
  { slug: 'pdf-to-jpg', name: 'PDF to JPG', category: 'Convert', description: 'Turn PDF pages into JPG images.', available: false },
  { slug: 'pdf-to-pdfa', name: 'PDF to PDF/A', category: 'Convert', description: 'Convert to the archival PDF/A format.', available: false },
  { slug: 'word-to-pdf', name: 'Word to PDF', category: 'Convert', description: 'Convert Word documents to PDF.', available: false },
  { slug: 'excel-to-pdf', name: 'Excel to PDF', category: 'Convert', description: 'Convert Excel spreadsheets to PDF.', available: false },
  { slug: 'powerpoint-to-pdf', name: 'PowerPoint to PDF', category: 'Convert', description: 'Convert presentations to PDF.', available: false },
  { slug: 'jpg-to-pdf', name: 'JPG to PDF', category: 'Convert', description: 'Convert JPG images into a PDF document.', available: true, multiFile: true, accept: 'image/jpeg,image/png' },
  { slug: 'html-to-pdf', name: 'HTML to PDF', category: 'Convert', description: 'Convert web pages to PDF.', available: false },
  { slug: 'edit-pdf', name: 'Edit PDF', category: 'Edit', description: 'Add text, images, and shapes to a PDF.', available: false },
  { slug: 'add-page-numbers', name: 'Add Page Numbers', category: 'Edit', description: 'Insert page numbers into your PDF.', available: true },
  { slug: 'add-watermark', name: 'Add Watermark', category: 'Edit', description: 'Stamp a text watermark on your PDF.', available: true, formField: { name: 'text', label: 'Watermark text', placeholder: 'CONFIDENTIAL' } },
  { slug: 'crop-pdf', name: 'Crop PDF', category: 'Edit', description: 'Crop the margins of a PDF.', available: true },
  { slug: 'sign-pdf', name: 'Sign PDF', category: 'Security', description: 'Add your signature to a PDF document.', available: false },
  { slug: 'protect-pdf', name: 'Protect PDF', category: 'Security', description: 'Add a password to secure your PDF.', available: false },
  { slug: 'unlock-pdf', name: 'Unlock PDF', category: 'Security', description: 'Remove a password from a protected PDF.', available: false },
  { slug: 'redact-pdf', name: 'Redact PDF', category: 'Security', description: 'Permanently black out sensitive content.', available: false },
  { slug: 'compare-pdf', name: 'Compare PDF', category: 'Security', description: 'Compare two PDF files for differences.', available: false },
  { slug: 'scan-to-pdf', name: 'Scan to PDF', category: 'Convert', description: 'Turn scanned images into a PDF.', available: false },
  { slug: 'pdf-to-pdfa-validate', name: 'Validate PDF/A', category: 'Optimize', description: 'Check a PDF for PDF/A compliance.', available: false },
  { slug: 'grayscale-pdf', name: 'Grayscale PDF', category: 'Optimize', description: 'Convert a color PDF to grayscale.', available: false },
  { slug: 'flatten-pdf', name: 'Flatten PDF', category: 'Edit', description: 'Flatten form fields and annotations.', available: true },
  { slug: 'delete-blank-pages', name: 'Delete Blank Pages', category: 'Organize', description: 'Automatically remove blank pages.', available: false },
  { slug: 'n-up-pdf', name: 'N-Up PDF', category: 'Organize', description: 'Combine multiple pages onto one sheet.', available: true, formField: { name: 'perSheet', label: 'Pages per sheet', type: 'select', options: [['2', '2 per sheet'], ['4', '4 per sheet']] } },
  { slug: 'pdf-to-text', name: 'PDF to Text', category: 'Convert', description: 'Extract plain text from a PDF.', available: true },
  { slug: 'chat-with-pdf', name: 'Chat with PDF', category: 'AI', description: 'Ask questions about your PDF using AI.', available: false },
  { slug: 'summarize-pdf', name: 'Summarize PDF', category: 'AI', description: 'Get an AI-generated summary of your PDF.', available: false },
];

export const CATEGORIES = [...new Set(TOOLS.map((t) => t.category))];
